### ISSUE TITLE
Darwinaized data and dictionary are not downloaded properly 

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bddwc.app#11]
![image](https://user-images.githubusercontent.com/16609623/71096565-38914e00-21b7-11ea-9129-85382552a36a.png)

**Comment by thiloshon** [comment]
This is not reproducible in both local and Binder. Can you please assure this @tom-gu?

<img width="495" alt="Screen Shot 2019-12-30 at 11 56 40 AM" src="https://user-images.githubusercontent.com/17028697/71570541-aa449280-2afb-11ea-9829-c1aacd572681.png">

**Comment by tom-gu** [comment]
@thiloshon it seems to work perfectly **only** for gbif data retrieved via the API :dizzy_face:
In binder- try non-gbif data (e.g. Puma concolor from iDigbio). 
Also, you can try any RDS file from the zip file attached.
[spooc_data_1r.zip](https://github.com/bd-R/bddwc.app/files/4012197/spooc_data_1r.zip)

**Comment by thiloshon** [comment]
This was caused because dataframes from different providers contained lists inside and NULL elements as list members. Thus writting to a csv file was failing.

Added a utility function in bdutilities and referred here to fix the issue.

**Comment by tom-gu** [comment]
Unfurtianly, in some cases, they can also have data frames within a list within a date frame :anguished: (e.g inaturalist).  Flattening the data won't work for all cases. I have a slick idea for a safe way of downloading the data. It will be easier to discuss it in our next meeting @thiloshon
