### ISSUE TITLE
Darwinaing without any dictionary (Darwin Cloud or user's) crushes the app

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bddwc.app#17]
![image.png](https://images.zenhubusercontent.com/59e62044a468affe6df6fea1/b420ab1f-4f33-4abd-836a-f75f083255d9)

**Comment by thiloshon** [comment]
Doesn't clicking 'Next' button from 'Configuring Dictionary' give a notification as following, stopping user from moving to next step?

![Screen Shot 2020-02-02 at 4.38.33 PM.png](https://images.zenhubusercontent.com/5a3a85828a75884b908bc424/b08f7901-2cf6-4d9e-8d52-bcd522a12a69)

**Comment by tom-gu** [comment]
Indeed, but you're assuming users always behave and follow the tabs order.
The same notification should appear when someone tries to Darwinaze without a dictionary. 
Can we activate the same notification so he will be directed to the Dictionary tab?
