### ISSUE TITLE
Adding hyperlinks to DwC reference guide 

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bddwc.app#18]
We should have a link to the DwC reference guide form each DwC data field name.
For example:
https://dwc.tdwg.org/terms/#accessRights

All these fields need to be a hyperlink:
![image.png](https://images.zenhubusercontent.com/59e62044a468affe6df6fea1/875e6170-ac96-42c9-bc69-2b79b374204c)

**Comment by thiloshon** [comment]
How about (i)? 
- Tomer

**Comment by tom-gu** [comment]
Marvelous! @thiloshon 
Is it possible to have the hyperlinks also in the manual renaming column, or is it problematic because of the dictionary creation?

![image](https://user-images.githubusercontent.com/16609623/75167457-0f002000-572e-11ea-926a-f894ec4c9101.png)

**Comment by tom-gu** [comment]
:ok_hand:
