### ISSUE TITLE
Data is not refreshed after a new download/upload

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bddwc.app#6]
In the Darwinize module, data is not refreshed after getting new data from a different provider and pressing:
![image](https://user-images.githubusercontent.com/16609623/66909999-6f5fb200-f016-11e9-9302-395a67b90bf4.png)
and then pressing:
 ![image](https://user-images.githubusercontent.com/16609623/66909853-27408f80-f016-11e9-9cb8-6b81045412e4.png)

**Comment by thiloshon** [comment]
Fixed with #8
