### ISSUE TITLE
Darwinizer Dictionary is showing all values instead of unused values only

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bddwc.app#7]
In the Darwinize module, the second column 'Darwinizer Dictionary' is showing all possible DwC names (174) instead of just the unused names. Otherwise, a user needs to go through many non-relevant names. See this:

![image](https://user-images.githubusercontent.com/16609623/66910729-cb770600-f017-11e9-8d8e-f7a3fa2edffb.png)

**Comment by thiloshon** [comment]
Fixed with #8
