### ISSUE TITLE
Moving functions from bddwc_utils.R to bdutilities

### ISSUE THREAD

**Issue by tom-gu** [bd-R/bddwc.app#9]
Some or all of the functions from [bddwc_utils.R](https://github.com/bd-R/bddwc.app/blob/master/R/bddwc_utils.R) need to move to bdutilities.
Especially `summarizeDataframe()`  that is being used by the data up/dl module...

**Comment by thiloshon** [comment]
Fixed the unlinked  summarizeDataframe function calls with https://github.com/bd-R/bdutilities.app/pull/12.
